-- Crear tablas

CREATE TABLE `asist_medi` (
  `CVE` bigint DEFAULT NULL,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `causaDef2017` (
  `CVE` text,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `causaDef2018` (
  `CVE` text,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `causaDef2019` (
  `CVE` text,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `causaDef2020` (
  `CVE` text,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `causaDef2021` (
  `CVE` text,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `lengua` (
  `CVE` bigint DEFAULT NULL,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ocupacion` (
  `CVE` bigint DEFAULT NULL,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataDefunciones2017` (
  `ent_regis` bigint DEFAULT NULL,
  `mun_regis` bigint DEFAULT NULL,
  `ent_resid` bigint DEFAULT NULL,
  `mun_resid` bigint DEFAULT NULL,
  `tloc_resid` bigint DEFAULT NULL,
  `loc_resid` bigint DEFAULT NULL,
  `ent_ocurr` bigint DEFAULT NULL,
  `mun_ocurr` bigint DEFAULT NULL,
  `tloc_ocurr` bigint DEFAULT NULL,
  `loc_ocurr` bigint DEFAULT NULL,
  `causa_def` text,
  `lista_mex` text,
  `sexo` bigint DEFAULT NULL,
  `edad` bigint DEFAULT NULL,
  `dia_ocurr` bigint DEFAULT NULL,
  `mes_ocurr` bigint DEFAULT NULL,
  `anio_ocur` bigint DEFAULT NULL,
  `dia_regis` bigint DEFAULT NULL,
  `mes_regis` bigint DEFAULT NULL,
  `anio_regis` bigint DEFAULT NULL,
  `dia_nacim` bigint DEFAULT NULL,
  `mes_nacim` bigint DEFAULT NULL,
  `anio_nacim` bigint DEFAULT NULL,
  `ocupacion` bigint DEFAULT NULL,
  `escolarida` bigint DEFAULT NULL,
  `edo_civil` bigint DEFAULT NULL,
  `presunto` bigint DEFAULT NULL,
  `ocurr_trab` bigint DEFAULT NULL,
  `lugar_ocur` bigint DEFAULT NULL,
  `necropsia` bigint DEFAULT NULL,
  `asist_medi` bigint DEFAULT NULL,
  `sitio_ocur` bigint DEFAULT NULL,
  `cond_cert` bigint DEFAULT NULL,
  `nacionalid` bigint DEFAULT NULL,
  `derechohab` bigint DEFAULT NULL,
  `embarazo` bigint DEFAULT NULL,
  `rel_emba` bigint DEFAULT NULL,
  `horas` bigint DEFAULT NULL,
  `minutos` bigint DEFAULT NULL,
  `capitulo` bigint DEFAULT NULL,
  `grupo` bigint DEFAULT NULL,
  `lista1` bigint DEFAULT NULL,
  `gr_lismex` text,
  `vio_fami` bigint DEFAULT NULL,
  `area_ur` bigint DEFAULT NULL,
  `edad_agru` bigint DEFAULT NULL,
  `complicaro` bigint DEFAULT NULL,
  `dia_cert` bigint DEFAULT NULL,
  `mes_cert` bigint DEFAULT NULL,
  `anio_cert` bigint DEFAULT NULL,
  `maternas` text,
  `lengua` bigint DEFAULT NULL,
  `cond_act` bigint DEFAULT NULL,
  `par_agre` bigint DEFAULT NULL,
  `ent_ocules` bigint DEFAULT NULL,
  `mun_ocules` bigint DEFAULT NULL,
  `loc_ocules` bigint DEFAULT NULL,
  `razon_m` bigint DEFAULT NULL,
  `dis_re_oax` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataDefunciones2018` (
  `ent_regis` bigint DEFAULT NULL,
  `mun_regis` bigint DEFAULT NULL,
  `ent_resid` bigint DEFAULT NULL,
  `mun_resid` bigint DEFAULT NULL,
  `tloc_resid` bigint DEFAULT NULL,
  `loc_resid` bigint DEFAULT NULL,
  `ent_ocurr` bigint DEFAULT NULL,
  `mun_ocurr` bigint DEFAULT NULL,
  `tloc_ocurr` bigint DEFAULT NULL,
  `loc_ocurr` bigint DEFAULT NULL,
  `causa_def` text,
  `lista_mex` text,
  `sexo` bigint DEFAULT NULL,
  `edad` bigint DEFAULT NULL,
  `dia_ocurr` bigint DEFAULT NULL,
  `mes_ocurr` bigint DEFAULT NULL,
  `anio_ocur` bigint DEFAULT NULL,
  `dia_regis` bigint DEFAULT NULL,
  `mes_regis` bigint DEFAULT NULL,
  `anio_regis` bigint DEFAULT NULL,
  `dia_nacim` bigint DEFAULT NULL,
  `mes_nacim` bigint DEFAULT NULL,
  `anio_nacim` bigint DEFAULT NULL,
  `ocupacion` bigint DEFAULT NULL,
  `escolarida` bigint DEFAULT NULL,
  `edo_civil` bigint DEFAULT NULL,
  `presunto` bigint DEFAULT NULL,
  `ocurr_trab` bigint DEFAULT NULL,
  `lugar_ocur` bigint DEFAULT NULL,
  `necropsia` bigint DEFAULT NULL,
  `asist_medi` bigint DEFAULT NULL,
  `sitio_ocur` bigint DEFAULT NULL,
  `cond_cert` bigint DEFAULT NULL,
  `nacionalid` bigint DEFAULT NULL,
  `derechohab` bigint DEFAULT NULL,
  `embarazo` bigint DEFAULT NULL,
  `rel_emba` bigint DEFAULT NULL,
  `horas` bigint DEFAULT NULL,
  `minutos` bigint DEFAULT NULL,
  `capitulo` bigint DEFAULT NULL,
  `grupo` bigint DEFAULT NULL,
  `lista1` bigint DEFAULT NULL,
  `gr_lismex` text,
  `vio_fami` bigint DEFAULT NULL,
  `area_ur` bigint DEFAULT NULL,
  `edad_agru` bigint DEFAULT NULL,
  `complicaro` bigint DEFAULT NULL,
  `dia_cert` bigint DEFAULT NULL,
  `mes_cert` bigint DEFAULT NULL,
  `anio_cert` bigint DEFAULT NULL,
  `maternas` text,
  `lengua` bigint DEFAULT NULL,
  `cond_act` bigint DEFAULT NULL,
  `par_agre` bigint DEFAULT NULL,
  `ent_ocules` bigint DEFAULT NULL,
  `mun_ocules` bigint DEFAULT NULL,
  `loc_ocules` bigint DEFAULT NULL,
  `razon_m` bigint DEFAULT NULL,
  `dis_re_oax` bigint DEFAULT NULL,
  `Unnamed: 59` double DEFAULT NULL,
  `escolarida.1` bigint DEFAULT NULL,
  `diferencias` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataDefunciones2019` (
  `ent_regis` bigint DEFAULT NULL,
  `mun_regis` bigint DEFAULT NULL,
  `ent_resid` bigint DEFAULT NULL,
  `mun_resid` bigint DEFAULT NULL,
  `tloc_resid` bigint DEFAULT NULL,
  `loc_resid` bigint DEFAULT NULL,
  `ent_ocurr` bigint DEFAULT NULL,
  `mun_ocurr` bigint DEFAULT NULL,
  `tloc_ocurr` bigint DEFAULT NULL,
  `loc_ocurr` bigint DEFAULT NULL,
  `causa_def` text,
  `lista_mex` text,
  `sexo` bigint DEFAULT NULL,
  `edad` bigint DEFAULT NULL,
  `dia_ocurr` bigint DEFAULT NULL,
  `mes_ocurr` bigint DEFAULT NULL,
  `anio_ocur` bigint DEFAULT NULL,
  `dia_regis` bigint DEFAULT NULL,
  `mes_regis` bigint DEFAULT NULL,
  `anio_regis` bigint DEFAULT NULL,
  `dia_nacim` bigint DEFAULT NULL,
  `mes_nacim` bigint DEFAULT NULL,
  `anio_nacim` bigint DEFAULT NULL,
  `ocupacion` bigint DEFAULT NULL,
  `escolarida` bigint DEFAULT NULL,
  `edo_civil` bigint DEFAULT NULL,
  `presunto` bigint DEFAULT NULL,
  `ocurr_trab` bigint DEFAULT NULL,
  `lugar_ocur` bigint DEFAULT NULL,
  `necropsia` bigint DEFAULT NULL,
  `asist_medi` bigint DEFAULT NULL,
  `sitio_ocur` bigint DEFAULT NULL,
  `cond_cert` bigint DEFAULT NULL,
  `nacionalid` bigint DEFAULT NULL,
  `derechohab` bigint DEFAULT NULL,
  `embarazo` bigint DEFAULT NULL,
  `rel_emba` bigint DEFAULT NULL,
  `horas` bigint DEFAULT NULL,
  `minutos` bigint DEFAULT NULL,
  `capitulo` bigint DEFAULT NULL,
  `grupo` bigint DEFAULT NULL,
  `lista1` bigint DEFAULT NULL,
  `gr_lismex` text,
  `vio_fami` bigint DEFAULT NULL,
  `area_ur` bigint DEFAULT NULL,
  `edad_agru` bigint DEFAULT NULL,
  `complicaro` bigint DEFAULT NULL,
  `dia_cert` bigint DEFAULT NULL,
  `mes_cert` bigint DEFAULT NULL,
  `anio_cert` bigint DEFAULT NULL,
  `maternas` text,
  `lengua` bigint DEFAULT NULL,
  `cond_act` bigint DEFAULT NULL,
  `par_agre` bigint DEFAULT NULL,
  `ent_ocules` bigint DEFAULT NULL,
  `mun_ocules` bigint DEFAULT NULL,
  `loc_ocules` bigint DEFAULT NULL,
  `razon_m` bigint DEFAULT NULL,
  `dis_re_oax` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataDefunciones2020` (
  `ent_regis` bigint DEFAULT NULL,
  `mun_regis` bigint DEFAULT NULL,
  `ent_resid` bigint DEFAULT NULL,
  `mun_resid` bigint DEFAULT NULL,
  `tloc_resid` bigint DEFAULT NULL,
  `loc_resid` bigint DEFAULT NULL,
  `ent_ocurr` bigint DEFAULT NULL,
  `mun_ocurr` bigint DEFAULT NULL,
  `tloc_ocurr` bigint DEFAULT NULL,
  `loc_ocurr` bigint DEFAULT NULL,
  `causa_def` text,
  `lista_mex` text,
  `sexo` bigint DEFAULT NULL,
  `edad` bigint DEFAULT NULL,
  `dia_ocurr` bigint DEFAULT NULL,
  `mes_ocurr` bigint DEFAULT NULL,
  `anio_ocur` bigint DEFAULT NULL,
  `dia_regis` bigint DEFAULT NULL,
  `mes_regis` bigint DEFAULT NULL,
  `anio_regis` bigint DEFAULT NULL,
  `dia_nacim` bigint DEFAULT NULL,
  `mes_nacim` bigint DEFAULT NULL,
  `anio_nacim` bigint DEFAULT NULL,
  `ocupacion` bigint DEFAULT NULL,
  `escolarida` bigint DEFAULT NULL,
  `edo_civil` bigint DEFAULT NULL,
  `presunto` bigint DEFAULT NULL,
  `ocurr_trab` bigint DEFAULT NULL,
  `lugar_ocur` bigint DEFAULT NULL,
  `necropsia` bigint DEFAULT NULL,
  `asist_medi` bigint DEFAULT NULL,
  `sitio_ocur` bigint DEFAULT NULL,
  `cond_cert` bigint DEFAULT NULL,
  `nacionalid` bigint DEFAULT NULL,
  `derechohab` bigint DEFAULT NULL,
  `embarazo` bigint DEFAULT NULL,
  `rel_emba` bigint DEFAULT NULL,
  `horas` bigint DEFAULT NULL,
  `minutos` bigint DEFAULT NULL,
  `capitulo` bigint DEFAULT NULL,
  `grupo` bigint DEFAULT NULL,
  `lista1` bigint DEFAULT NULL,
  `gr_lismex` text,
  `vio_fami` bigint DEFAULT NULL,
  `area_ur` bigint DEFAULT NULL,
  `edad_agru` bigint DEFAULT NULL,
  `complicaro` bigint DEFAULT NULL,
  `dia_cert` bigint DEFAULT NULL,
  `mes_cert` bigint DEFAULT NULL,
  `anio_cert` bigint DEFAULT NULL,
  `maternas` text,
  `lengua` bigint DEFAULT NULL,
  `cond_act` bigint DEFAULT NULL,
  `par_agre` bigint DEFAULT NULL,
  `ent_ocules` bigint DEFAULT NULL,
  `mun_ocules` bigint DEFAULT NULL,
  `loc_ocules` bigint DEFAULT NULL,
  `razon_m` bigint DEFAULT NULL,
  `dis_re_oax` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataDefunciones2021` (
  `ent_regis` bigint DEFAULT NULL,
  `mun_regis` bigint DEFAULT NULL,
  `ent_resid` bigint DEFAULT NULL,
  `mun_resid` bigint DEFAULT NULL,
  `tloc_resid` bigint DEFAULT NULL,
  `loc_resid` bigint DEFAULT NULL,
  `ent_ocurr` bigint DEFAULT NULL,
  `mun_ocurr` bigint DEFAULT NULL,
  `tloc_ocurr` bigint DEFAULT NULL,
  `loc_ocurr` bigint DEFAULT NULL,
  `causa_def` text,
  `lista_mex` text,
  `sexo` bigint DEFAULT NULL,
  `edad` bigint DEFAULT NULL,
  `dia_ocurr` bigint DEFAULT NULL,
  `mes_ocurr` bigint DEFAULT NULL,
  `anio_ocur` bigint DEFAULT NULL,
  `dia_regis` bigint DEFAULT NULL,
  `mes_regis` bigint DEFAULT NULL,
  `anio_regis` bigint DEFAULT NULL,
  `dia_nacim` bigint DEFAULT NULL,
  `mes_nacim` bigint DEFAULT NULL,
  `anio_nacim` bigint DEFAULT NULL,
  `ocupacion` bigint DEFAULT NULL,
  `escolarida` bigint DEFAULT NULL,
  `edo_civil` bigint DEFAULT NULL,
  `presunto` bigint DEFAULT NULL,
  `ocurr_trab` bigint DEFAULT NULL,
  `lugar_ocur` bigint DEFAULT NULL,
  `necropsia` bigint DEFAULT NULL,
  `asist_medi` bigint DEFAULT NULL,
  `sitio_ocur` bigint DEFAULT NULL,
  `cond_cert` bigint DEFAULT NULL,
  `nacionalid` bigint DEFAULT NULL,
  `derechohab` bigint DEFAULT NULL,
  `embarazo` bigint DEFAULT NULL,
  `rel_emba` bigint DEFAULT NULL,
  `horas` bigint DEFAULT NULL,
  `minutos` bigint DEFAULT NULL,
  `capitulo` bigint DEFAULT NULL,
  `grupo` bigint DEFAULT NULL,
  `lista1` bigint DEFAULT NULL,
  `gr_lismex` text,
  `vio_fami` bigint DEFAULT NULL,
  `area_ur` bigint DEFAULT NULL,
  `edad_agru` bigint DEFAULT NULL,
  `complicaro` bigint DEFAULT NULL,
  `dia_cert` bigint DEFAULT NULL,
  `mes_cert` bigint DEFAULT NULL,
  `anio_cert` bigint DEFAULT NULL,
  `maternas` text,
  `lengua` bigint DEFAULT NULL,
  `cond_act` bigint DEFAULT NULL,
  `par_agre` bigint DEFAULT NULL,
  `ent_ocules` bigint DEFAULT NULL,
  `mun_ocules` bigint DEFAULT NULL,
  `loc_ocules` bigint DEFAULT NULL,
  `razon_m` bigint DEFAULT NULL,
  `dis_re_oax` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataEstimaciones` (
  `RENGLON` bigint DEFAULT NULL,
  `CLAVE` bigint DEFAULT NULL,
  `CLAVE_ENT` bigint DEFAULT NULL,
  `NOM_ENT` text,
  `MUN` text,
  `SEXO` text,
  `AÑO` bigint DEFAULT NULL,
  `EDAD_QUIN` text,
  `POB` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rawDataHabitantes` (
  `Codigo_Municipio` text,
  `Nombre_Municipio` text,
  `Cantidad_Habitantes` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sexo` (
  `CVE` bigint DEFAULT NULL,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sitio_ocur` (
  `CVE` bigint DEFAULT NULL,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tamanio_loc` (
  `CVE` bigint DEFAULT NULL,
  `DESCRIP` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;